### PR TITLE
windows installer

### PR DESCRIPTION
**Pull request by tillkrischer**
Here is my attempt at a windows installer. 

First build `browserpass-windows64.exe`, then build the Visual Studio Project (you need the "Microsoft Visual Studio Installer Projects" extension).
The installer will be in `setup\Browserpass Setup\Debug\browserpass.msi`

### CODE REVIEW

**Comment by maximbaz** [comment]
I love the initiative!

Before we spend more time with this, I need to investigate if this is usable on Linux, as much as I prefer to have a proper `.msi` installed, I need to be able to compile it on Linux and I don't have a Windows machine.

Do you maybe already know if this possible?

There's a package called `msitools` for Linux, so I think one or another way we will be able to achieve this.

**Comment by tillkrischer** [comment]
It gets complicated because of the dynamic elements, where depending onthe user choices in the installer you need to write different files. I am writing custom c# for that, not sure if that's possible on Linux. 

A possible approach could be to work backwards from my msi, using msidump, then you reassemble it on Linux using msibuild. The only thing that changes between releases is the .exe anyways.

**Comment by maximbaz** [comment]
If C# code causes issues, maybe we could remove everything custom by simplifying and removing all options, just letting the MSI install _everything_? For example:

```
C:\Program Files\Browserpass\<contents of browserpass-windows64-3.0.6.zip>
C:\Program Files\Browserpass (WSL)\<contents of browserpass-linux64-3.0.6.zip> + <wsl.bat>
```

(by the way, notice that WSL installation requires the contents of `linux64.zip`, not `windows64.zip`)

I realizee that one or another way you need to put proper path into `hosts-*.json` files (which is also different for "regular" and WSL installation, so you need to have different `browser-files` folder in `C:\Program Files\Browserpass\` and `C:\Program Files\Browserpass (WSL)\`.

Maybe we can add a powershell script that will run automatically after installation is finished, which would:

- Put proper path to windows binary in `C:\Program Files\Browserpass\browser-files\*.json
- Put proper path to wsl wrapper in `C:\Program Files\Browserpass (WSL)\browser-files\*.json
- Configure all browsers in registry?

This way hopefully it makes MSI much simpler to create on Linux.

**Comment by maximbaz** [comment]
Closed by #61, however simpler, I can easily maintain and build it on Linux, exactly what I need 👍 

Thanks again 🎉

**Pull request closed without merging**
