### PR TITLE
Add more locations to check for default store path

### LINKED ISSUE #107: Check gopass default store location
### General information

-   Operating system + version: Arch Linux rolling
-   Browser + version: Firefox 90.0.2
-   Information about the host app:
    -   How did you install it?
      Installed via a package manager
    -   If installed an official release, put a version (`$ browserpass --version`): 3.0.7
-   Information about the browser extension:
    -   How did you install it?
        webstore
    -   Browserpass extension version as reported by your browser: 3.7.2

---

### What should happen?

I would expect browserpass to also check the default password store location of gopass (`~/.local/share/gopass/stores/root`) by default.

### What happened instead?

browserpass doesn't work out of the box with gopass' default store location. `PASSWORD_STORE_DIR` has to be set.

### PR DESCRIPTION
**Pull request by cloudlena**
Fixes #107

### CODE REVIEW

**Comment by maximbaz** [comment]
Hey @mastertinner, thanks for a quick PR! We had a quick discussion internally and decided to go with another approach, we will keep the list of such lookup paths on extension side and rewrite the native component to make it generic - it is our goal to change native host as little as possible, such that if gopass changes folders lookup, if pass finally decides something on #95 or if yet another tool becomes popular, we will be able to simply add support to these new locations in the extension, without having to change native component.

Sorry that I initially gave you a different suggestion, and thanks again for the PR! I'll have a look into it and ping you once it's ready, so that you can test if you'd like to!

**Comment by mastertinner** [comment]
OK, sounds good. So should I close this PR?

**Comment by maximbaz** [comment]
It's fine to keep it for now, I'll reference it in that other PR and it will be closed then :)

**Comment by mastertinner** [comment]
@maximbaz, is there any progress on this matter?

**Pull request closed without merging**
