### PR TITLE
Add openSUSE to provided packages list

### PR DESCRIPTION
**Pull request by tux93**

### CODE REVIEW

**Comment by maximbaz** [comment]
Thanks @tux93! Is it you who packaged it, or someone else? I would simply like give some suggestions for the packager if I knew who that was 🙂

**Comment by maximbaz** [comment]
Oh sorry I clicked "Merge" too soon 😛 OK to fix in master?

**Comment by erayd** [comment]
@maximbaz Go for it :+1:

**Comment by erayd** [comment]
@maximbaz We should probably clarify that Debian is just Debian Sid (unstable) too.

**Comment by tux93** [comment]
> Thanks @tux93! Is it you who packaged it, or someone else? I would simply like give some suggestions for the packager if I knew who that was

Yes I am, let me know you suggestions

**Pull request merged**
